#!/usr/bin/env python3
"""Compress photos dropped in gallery-inbox/ and publish them to the Photography gallery.

Usage: python3 scripts/process_gallery.py

For every image in gallery-inbox/, this: fixes rotation from EXIF, downscales to a
2000px long edge, saves it as WebP into public/photos/gallery/, deletes the original
from the inbox, and regenerates data/gallery.js so the site picks it up automatically.
"""
import re
import sys
from pathlib import Path

from PIL import Image, ImageOps

ROOT = Path(__file__).resolve().parent.parent
INBOX = ROOT / "gallery-inbox"
DEST = ROOT / "public" / "photos" / "gallery"
MANIFEST = ROOT / "data" / "gallery.js"

MAX_LONG_EDGE = 2000
WEBP_QUALITY = 85
SUPPORTED_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".tif", ".tiff", ".bmp"}
IGNORED_NAMES = {"readme.md"}
NAME_PATTERN = re.compile(r"gallery-(\d+)\.webp$")


def next_index():
    indices = [
        int(match.group(1))
        for path in DEST.glob("gallery-*.webp")
        if (match := NAME_PATTERN.match(path.name))
    ]
    return (max(indices) + 1) if indices else 1


def process_image(src_path, index):
    with Image.open(src_path) as img:
        img = ImageOps.exif_transpose(img)
        img = img.convert("RGB")
        long_edge = max(img.size)
        if long_edge > MAX_LONG_EDGE:
            scale = MAX_LONG_EDGE / long_edge
            new_size = (round(img.size[0] * scale), round(img.size[1] * scale))
            img = img.resize(new_size, Image.LANCZOS)
        dest_path = DEST / f"gallery-{index}.webp"
        img.save(dest_path, "WEBP", quality=WEBP_QUALITY)
        return dest_path


def write_manifest():
    photos = sorted(
        DEST.glob("gallery-*.webp"),
        key=lambda p: int(NAME_PATTERN.match(p.name).group(1)),
    )
    lines = [
        "// Auto-generated by scripts/process_gallery.py — do not edit by hand.",
        "const gallery = [",
    ]
    for path in photos:
        lines.append(f'  {{ src: "/photos/gallery/{path.name}", alt: "Photograph by Ricky Vu" }},')
    lines.append("];")
    lines.append("")
    lines.append("export default gallery;")
    lines.append("")
    MANIFEST.write_text("\n".join(lines))


def main():
    INBOX.mkdir(exist_ok=True)
    DEST.mkdir(parents=True, exist_ok=True)

    all_files = sorted(
        p
        for p in INBOX.iterdir()
        if p.is_file() and not p.name.startswith(".") and p.name.lower() not in IGNORED_NAMES
    )
    candidates = [p for p in all_files if p.suffix.lower() in SUPPORTED_SUFFIXES]
    unsupported = [p.name for p in all_files if p.suffix.lower() not in SUPPORTED_SUFFIXES]

    if unsupported:
        print("Skipped (unsupported format, export to JPG/PNG first):")
        for name in unsupported:
            print(f"  - {name}")

    if not candidates:
        print("No new photos found in gallery-inbox/.")
        write_manifest()
        return

    index = next_index()
    processed = []
    for src_path in candidates:
        try:
            dest_path = process_image(src_path, index)
        except Exception as exc:  # noqa: BLE001 - report and keep processing the rest
            print(f"Skipped {src_path.name}: {exc}", file=sys.stderr)
            continue
        src_path.unlink()
        processed.append((src_path.name, dest_path.name))
        index += 1

    write_manifest()

    for original, compressed in processed:
        print(f"{original} -> public/photos/gallery/{compressed}")
    print(f"Done. {len(processed)} photo(s) added to the gallery.")


if __name__ == "__main__":
    main()
